---
version: '3'
services:
  opensearch-node-2.x:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node-2.x
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node-2.x
      - discovery.seed_hosts=opensearch-node-2.x
      - cluster.initial_cluster_manager_nodes=opensearch-node-2.x
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards-2.x
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      OPENSEARCH_HOSTS: '["http://opensearch-node-2.x:9200"]'
    networks:
      - opensearch-net
networks:
  opensearch-net:
