from opensearchpy import Byte, Document, Date, Integer, Keyword, Long, Short


class CommonInformation(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    fw_ver = Keyword()
    system_uptime = Keyword()
    cpu_usage = Byte()
    memory_usage = Byte()
    session_usage = Integer()
    max_session = Integer()
    data_cpu_usage = Byte()


class ApplicationPatrol(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    app_category = Keyword()
    app_name = Keyword()
    match_rule_number = Keyword()
    app_action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class Traffic(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    traffic_duration = Long()
    traffic_app_name = Keyword()
    rx = Long()
    tx = Long()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    traffic_protocol = Keyword()
    client_host = Keyword()
    snat_ip = Keyword()
    snat_port = Integer()
    dnat_ip = Keyword()
    dnat_port = Integer()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class AntiMalware(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    virus_name = Keyword()
    file_name = Keyword()
    match_rule_number = Keyword()
    action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    virus_hash = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class ThreatProtection(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    signature_id = Keyword()
    signature = Keyword()
    match_rule_number = Keyword()
    threat_action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    threat_type = Keyword()
    severity = Byte()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class MailProtection(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    mail_protocol = Keyword()
    mail_malware = Keyword()
    mail_from = Keyword()
    match_rule_number = Keyword()
    mail_subject = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    mail_action = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class WebProtection(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    web_category = Keyword()
    website = Keyword()
    match_rule_number = Keyword()
    web_action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class APManaged(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    ap_name = Keyword()
    ap_action = Keyword()
    station_mac = Keyword()
    reason = Keyword()
    ap_max_station = Integer()
    ap_rx_error_count = Long()
    ap_tx_retry_count = Long()
    ap_band = Keyword()
    signal_strength = Keyword()
    station_tx_pkt = Long()
    station_rx_pkt = Long()
    station_ssid = Keyword()
    station_ip = Keyword()


class DHCPEvent(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    ip = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    dhcp_action = Keyword()


class SystemServiceStatus(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    service_name = Keyword()
    service_status = Keyword()
    is_sync_timezone = Keyword()
    is_sync_daylight = Keyword()
    is_enable_daylight = Keyword()
    daylight_duration = Keyword()
    daylight_offset = Keyword()
    timezone_location = Keyword()


class VPNConnection(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(format='epoch_millis', default_timezone='UTC')
    vpn_gateway = Keyword()
    connection_name = Keyword()
    vpn_action = Keyword()
    vpn_type = Keyword()
    srcip = Keyword()
    dstip = Keyword()
    assigned_ip = Keyword()
    vpn_user = Keyword()
    client_host = Keyword()
    vpn_inbound = Long()
    vpn_outbound = Long()
    vpn_uptime = Long()
    packet_status = Keyword()
    ssl_app_name = Keyword()
    connection = Keyword()
    ike_version = Keyword()
    fail_count = Integer()


class InterfaceStatistic(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    interface_name = Keyword()
    interface_status = Keyword()
    tx_pkt = Long()
    rx_pkt = Long()
    collision = Long()
    tx_rate = Long()
    rx_rate = Long()


class UserLogin(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    user_type = Keyword()
    user = Keyword()
    client_mac = Keyword()
    login_type = Keyword()
    login_action = Keyword()
    srcip = Keyword()
    dstip = Keyword()
    ref_user = Keyword()
    ref_user_type = Keyword()
    ref_user_changed_value = Keyword()


class AppTraffic(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    app_name = Keyword()
    forward_size = Long()
    drop_size = Long()
    reject_size = Long()
    auto_conn = Long()
    inbound = Long()
    outbound = Long()


class AppPatrolUsageStatistics(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    app_name = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    app_protocol = Keyword()
    establish_timestamp = Integer()
    send_increase_bytes = Long()
    receive_increase_bytes = Long()


class AntiBotnet(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    botnet_action = Keyword()
    botnet_name = Keyword()
    botnet_url = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    botnet_category = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class Sandbox(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    sandbox_protocol = Keyword()
    mail_from = Keyword()
    mail_to = Keyword()
    mail_subject = Keyword()
    sandbox_url = Keyword()
    file_name = Keyword()
    hash_type = Keyword()
    hash_value = Keyword()
    sandbox_score = Short()
    sandbox_action = Keyword()
    judge = Keyword()
    sandbox_uuid = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    file_type = Keyword()
    risk_level = Keyword()
    sandbox_file_id = Keyword()
    query_dc_timestamp = Integer()
    sandbox_action_setting = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class SandboxStatistics(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    malicious_count = Integer()
    suspicious_count = Integer()
    clean_count = Integer()
    processing_count = Integer()
    processed_count = Integer()
    other_count = Integer()


class DeviceEventType(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    device_event_type = Keyword()


class SystemEventType(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    system_event_type = Keyword()


class Reputation(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    action = Keyword()
    risk_level = Keyword()
    category_name = Keyword()
    hit_categories = Keyword()
    risk_score = Integer()
    risk_ip = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class DNSFilter(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    category_name = Keyword()
    query_type = Keyword()
    fqdn = Keyword()
    match_rule_number = Keyword()
    match_rule_action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    dstport = Integer()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class DNSContentFilter(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    category_name = Keyword()
    query_type = Keyword()
    fqdn = Keyword()
    match_rule_number = Keyword()
    match_rule_action = Keyword()
    srcip = Keyword()
    srcport = Integer()
    dstip = Keyword()
    user = Keyword()
    client_host = Keyword()
    client_mac = Keyword()
    client_dev_category = Keyword()
    client_dev_type = Keyword()
    client_dev_os = Keyword()
    client_dev_os_version = Keyword()
    client_dev_manufacture = Keyword()
    astra_mail = Keyword()
    astra_user_id = Keyword()
    astra_node_id = Keyword()


class DUTScanStatistics(Document):
    device_time = Date(format='yyyy-MM-dd HH:mm:ss', default_timezone='UTC')
    utc_time = Date(default_timezone='UTC')
    anti_virus = Integer()
    idp = Integer()
    anti_spam = Integer()
    content_filter = Integer()
    url_threat_filter = Integer()
    sandboxing = Integer()
    ip_reputation = Integer()
    dns_filter = Integer()
    dns_content_filter = Integer()
